// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBpleYwqPA_idv1h53OON431jTgAhZVQk',
    appId: '1:130697172172:web:7cd45a61a71c20e14c1e69',
    messagingSenderId: '130697172172',
    projectId: 'rarecrew-todo',
    authDomain: 'rarecrew-todo.firebaseapp.com',
    storageBucket: 'rarecrew-todo.appspot.com',
    measurementId: 'G-ZXT0BZD2MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRKYkflztU8EYq3xqflCQgpBY1LvpIQU',
    appId: '1:130697172172:android:2fcb785e75af9f334c1e69',
    messagingSenderId: '130697172172',
    projectId: 'rarecrew-todo',
    storageBucket: 'rarecrew-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdafv-Doo6pHwuHGBrIWbnZeAsUCE4C0I',
    appId: '1:130697172172:ios:fb26d188500ffd7a4c1e69',
    messagingSenderId: '130697172172',
    projectId: 'rarecrew-todo',
    storageBucket: 'rarecrew-todo.appspot.com',
    iosBundleId: 'com.rarecrew.rarecrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdafv-Doo6pHwuHGBrIWbnZeAsUCE4C0I',
    appId: '1:130697172172:ios:88a50aa5b68f8e454c1e69',
    messagingSenderId: '130697172172',
    projectId: 'rarecrew-todo',
    storageBucket: 'rarecrew-todo.appspot.com',
    iosBundleId: 'com.rarecrew.rarecrew.RunnerTests',
  );
}
